########################################################################################################################
########################################################################################################################
#
#           Registration
#
#
########################################################################################################################
########################################################################################################################

# lovegov
from lovegov.modernpolitics.initialize import *

#-----------------------------------------------------------------------------------------------------------------------
# Register from email form
#-----------------------------------------------------------------------------------------------------------------------
def registerHelper(name, email, password, day, month, year, zip):

    user = createUser(name,email,password)
    user.backend = 'django.contrib.auth.backends.ModelBackend'
    user.save()

    user_profile = user.user_profile
    if zip:
        user_profile.setZipCode(zip)

    dob = datetime.date(year=year, month=month, day=day)
    user_profile.setDOB(dob)

    return user_profile

#-----------------------------------------------------------------------------------------------------------------------
# Resets a users password and sends an email.
#-----------------------------------------------------------------------------------------------------------------------
def resetPassword(user):
    password = generateRandomPassword(10)
    print ("password: " + password)
    user.set_password(password)
    user.save()
    sendPasswordChangeEmail(user, password)

#-----------------------------------------------------------------------------------------------------------------------
# Creates a user for the alpha based on name and email (with autogenerated password)
# args: name, email
#-----------------------------------------------------------------------------------------------------------------------
def createFBUser(name, email):
    password = generateRandomPassword(10)
    control = createUser(name, email, password)
    return control

def createTwitterUser(name, email, vals={}):
    password = generateRandomPassword(10)
    control = createUser(name, email, password)
    return control

#-------------------------------------------------------------------------------------------------------------------
# creates a new userprofile from name, email and password, along with controlling user to manage this profile.
# - name, email, password
#-------------------------------------------------------------------------------------------------------------------
def createUser(name, email, password,active=True):
    # NORMAL CASE
    if not ControllingUser.objects.filter(username=email):
        control = ControllingUser.objects.create_user(username=email, email=email, password=password)
        control.is_active = active
        control.save()
        logger.debug("created control: " + control.email)
        user_profile = createUserHelper(control=control, name=name, active=active)
        logger.debug("created userpof: " + user_profile.get_name())
        control.user_profile = user_profile
        control.save()
        return control

    # SPECIAL CASE FOR CREATING USERS DURING PARSE SCRIPTS
    else:
        logger.error("DUPLICATE USERNAME REGISTRATION.")
        splitted = email.split("@")
        if len(splitted)==1:
            c = ControllingUser.objects.get(username=email)
            c.delete()
            return createUser(name, email, password, active)
        else:
            if splitted[1] == "lovegov.com":
                c = ControllingUser.objects.get(username=email)
                c.delete()
                return createUser(name, email, password, active)

#-------------------------------------------------------------------------------------------------------------------
# creates a new userprofile from name, email and password, along with controlling user to manage this profile.
# - name, email, passwordtype='userProfile'
#-------------------------------------------------------------------------------------------------------------------
def createUserHelper(control,name,active=True):

    user_profile = UserProfile()

    names = name.split()
    num_names = len(names)
    first_name = ""
    last_name = ""
    for i,name in enumerate(names):
        name = str(name)
        if i==0:
            first_name = str.capitalize(name)
        elif i < (num_names-1):
            first_name += " " + str.capitalize(name)
        else:
            last_name = str.capitalize(name)
    user_profile.first_name = first_name
    user_profile.last_name = last_name

    user_profile.email = control.email
    user_profile.username = control.username

    # active
    user_profile.is_active = active
    user_profile.confirmation_link = str(random.randint(1,9999999999999999999))

    # worldview
    world_view = WorldView()
    world_view.save()
    user_profile.view = world_view
    user_profile.save()

    # alias
    user_profile.makeAlias()

    # connections group and lovegov group and join or create network group
    user_profile.createIFollowGroup()
    user_profile.createFollowMeGroup()
    user_profile.joinLoveGovGroup()

    # auto subscribe to some groups?
    user_profile.autoSubscribe()

    # associate with control
    user_profile.user = control
    user_profile.save()

    # get notifications that were associated with this user's email prior to registration
    notifications = Notification.objects.filter(notify_email=user_profile.email)
    for n in notifications:
        n.claimedByProfile(user_profile)

    # send confirmation email
    sendConfirmationEmail(user_profile)

    # return user prof
    return user_profile
